### ISSUE TITLE
Buttons Disabled on Mobile

### ISSUE THREAD

**Issue by yosoyju** [aegis41/js-carrots-or-garbage#28]
![image](https://github.com/user-attachments/assets/403ff26c-b6aa-4bf0-afcb-f3b660fbf04f)

Using Chrome on iOS. View Statistics button is enabled but unstyled. All other buttons are disabled.

**Comment by aegis41** [comment]
local savegame logic broken. fix identified and incoming.

**Comment by aegis41** [comment]
issue appears to be resolved. feel free to verify.
